package com.collection;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;

public class ArrayListgetAllnonPresentElement {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
	
		List<String> scacCodesnew=new LinkedList<String>(Arrays.asList("ABFS","AIR EXPRESS INT","AIRX EXP","AIRX EXP SAT","AIRX NAS","AIRX SDS","ARX1","ARX2","ARXA","CEV1","CEV2","CEV3","CEVE","CEVG","CEVN","CEVV","CPEX","CQRG","CUSP","CUST","DAFG","DHLE","DYTY","EGL3","EMRY","EMRY1","EMRY1 PM","EMRY2","FASP","FEDX 2DAY","FEDX 2DAY FRT","FEDX 2DAY SAT","FEDX FO BOX","FEDX FO LETTER","FEDX INT PRI","FEDX ON FRT","FEDX PO","FEDX PO LETTER","FEDX PO SAT","FEDX SAVER","FEDX SAVER FRT","FEDX SO","FEDX SO LETTER","FEXF","FGH2","FGH3","FGH7","FHD2","FHD3","FLC1","FLC2","FLC3","FSPB","FX01","FX2D","FXAF","FXAM","FXC1","FXC2","FXC3","FXCA","FXCG","FXCS","FXDS","FXEI","FXG2","FXG3","FXG7","FXGH","FXGR","FXIE","FXIP","FXL1","FXL2","FXL3","FXLE","FXLG","FXNE","FXNL","FXPI","FXSA","FXSP","FXSV","G2DAYP","G3DAYP","GFX1","GFX2","GFX3","GFXA","GFXG","GGRNDP","GOVNTA","GOVNTP","HMES","ODFL","OSM1","P_SCAC","PREX","PRGR","PRLT","PTWT","RDW1","RDW2","RDW3","RDWG","RDWT","RDWY","ROADWAY","RWGD","SAIA","SEMRYP","SFEV1P","SFEV2P","SFEVAA","SFLC1P","SFLC2P","SFLC3P","SFX01P","SFX2DP","SFX3DP","SFXAMA","SFXC1P","SFXC2P","SFXC3P","SFXCAA","SFXCGP","SFXCSA","SFXEGHP","SFXEGRP","SFXEIEP","SFXEVAA","SFXGHP","SFXGRP","SFXIEP","SFXIPP","SFXL1P","SFXL2P","SFXL3P","SFXSAA","SFXSAP","SFXSVP","SPLT","SRDW1P","SRDW2P","SRDW3P","SRDWGP","SRDWTP","SRDWYP","SUPC3P","SUPCAA","SUPCBP","SUPCGP","SUPCRP","SUPCSP","SUPH1P","SUPH2P","SUPH3P","SUPHGP","SUPICP","SUPIEP","SUPIXP","SUPS3P","SUPSAA","SUPSBP","SUPSGP","SUPSRP","SUPSSP","TTMS","UPAM","UPC3","UPCA","UPCB","UPCG","UPCR","UPCS","UPD2","UPS","UPS 2ND DAY AM","UPS 3DAY","UPS BLUE","UPS BLUE AM","UPS GROUND","UPS RED","UPS RED PM","UPS SATURDAY","UPS1","UPS2","UPS3","UPSA","UPSB","UPSE","UPSF","UPSG","UPSM","UPSR","UPSS","UPSV","UPSZ","USFC","USP1","USPP","USPS","VITRAN"));
		  List<String> c=Arrays.asList("SUPC3P","SUPCAA","SUPCBP","SUPCGP","SUPCRP","SUPCSP","SUPH1P","SUPH2P","SUPH3P",
				    "SUPHGP","SUPICP","SUPIEP","SUPIXP","SUPS3P","SUPSAA","SUPSBP","SUPSGP","SUPSRP","SUPSSP","UPC3","UPCA","UPCB","UPCG",
				    "UPCR","UPCS","UPS","UPS2NDDAYAM","UPS3","UPS3DAY","UPSA","UPSB","UPSBLUE","UPSBLUEAM","UPSG","UPSGROUND","UPSR",
				    "UPSRED","UPSREDPM","UPSS","UPSSATURDAY","AIREXPRESSINT","AIRXEXP","AIRXEXPSAT","AIRXNAS","AIRXSDS","ARX1","ARX2",
				    "ARXA","EMRY","EMRY1","EMRY1PM","EMRY2","SEMRYP","VITRAN","RDW1","RDW2","RDW3","RDWG","RDWT","RDWY","ROADWAY",
				    "SRDW1P","SRDW2P","SRDW3P","SRDWGP","SRDWTP","SRDWYP","RWGD","FEDX2DAY","FEDX2DAYFRT","FEDX2DAYSAT","FEDXFOBOX",
				    "FEDXFOLETTER","FEDXINTPRI",   "FEDXONFRT","FEDXPO","FEDXPOLETTER","FEDXPOSAT","FEDXSAVER","FEDXSAVERFRT","FEDXSO",
				    "FEDXSOLETTER","FLC1","FLC2","FLC3","FX01","FX2D","FXAM","FXC1","FXC2","FXC3","FXCA","FXCG","FXGH","FXGR",
				    "FXIP","FXL1","FXL2","FXL3","FXSA","FXSV","SFEV1P","SFEV2P","SFEVAA","SFLC1P","SFLC2P","SFLC3P","SFX01P",
				    "SFX2DP","SFXAMA","SFXC1P","SFXC2P","SFXC3P","SFXCAA","SFXCGP","SFXCSA","SFXEVAA","SFXEGHP","SFXEGRP","SFXEIEP",
				    "SFXIEP","SFXIPP","SFXIPP","SFXL1P","SFXL2P","SFXL3P","SFXSAA","SFXSAP","SFXSVP","SFXGRP","SFXGHP","FXCS","FXG3","FGH3",
				    "FXG2","FGH2","FXLG","FXLE","INFC","G2DAYP","SFX3DP","G3DAYP","GGRNDP","GOVNTA","GOVNTP","FXIE","FGH7","FXNL","CEVE","CEVG",
				    "CEVN","CEV1","CEV2","CEV3","USPP");
//		 
		 
	List<String> a=new ArrayList<String>();
	a.add("s");
	List<String> b=new ArrayList<String>();
	a.add("s");
	a.add("a");
	b.add("s");
	b.add("w");
	scacCodesnew.removeAll(c);
	System.out.println(b.size());
	System.out.println(scacCodesnew);
		  b.removeAll(a);
		  System.out.println(b);
	}

	
	
	
}
